// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcuz-gjdfF0_sMeJHQq5SaeAAddSeDJk0',
    appId: '1:293461002643:web:f09e8ba9c733289ff5c066',
    messagingSenderId: '293461002643',
    projectId: 'agrobuzz-2c266',
    authDomain: 'agrobuzz-2c266.firebaseapp.com',
    storageBucket: 'agrobuzz-2c266.firebasestorage.app',
    measurementId: 'G-JST5JX00Z3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuPg-g7Oe64EnjO9-RWcZJU4NfD8keII4',
    appId: '1:293461002643:android:fd97c48748d89043f5c066',
    messagingSenderId: '293461002643',
    projectId: 'agrobuzz-2c266',
    storageBucket: 'agrobuzz-2c266.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBJdaLO9Pg5o5D2MzgecKcP_8OnOzhEfo',
    appId: '1:293461002643:ios:59fead3054da0f6df5c066',
    messagingSenderId: '293461002643',
    projectId: 'agrobuzz-2c266',
    storageBucket: 'agrobuzz-2c266.firebasestorage.app',
    iosClientId: '293461002643-caa8d76ngpclug01mjj8nlit78gclju1.apps.googleusercontent.com',
    iosBundleId: 'com.example.agroBuzz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBJdaLO9Pg5o5D2MzgecKcP_8OnOzhEfo',
    appId: '1:293461002643:ios:59fead3054da0f6df5c066',
    messagingSenderId: '293461002643',
    projectId: 'agrobuzz-2c266',
    storageBucket: 'agrobuzz-2c266.firebasestorage.app',
    iosClientId: '293461002643-caa8d76ngpclug01mjj8nlit78gclju1.apps.googleusercontent.com',
    iosBundleId: 'com.example.agroBuzz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcuz-gjdfF0_sMeJHQq5SaeAAddSeDJk0',
    appId: '1:293461002643:web:703ee35d0d1e6e26f5c066',
    messagingSenderId: '293461002643',
    projectId: 'agrobuzz-2c266',
    authDomain: 'agrobuzz-2c266.firebaseapp.com',
    storageBucket: 'agrobuzz-2c266.firebasestorage.app',
    measurementId: 'G-REZNSKY74K',
  );
}
